# Generated by Django 5.1.1 on 2025-10-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfService', '0003_mesa_reserva_expira_em_mesa_reservada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ATENDENTE', 'Atendente'), ('GERENTE', 'Gerente'), ('CLIENTE', 'Cliente')], default='ATENDENTE', max_length=20),
        ),
    ]
