# Generated by Django 5.1.1 on 2025-10-04 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfService', '0006_remove_pedido_atendente_pedido_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em preparo'), ('C', 'Concluído'), ('F', 'Faturado')], default='E', max_length=1),
        ),
    ]
