# Generated by Django 5.2 on 2025-10-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfService', '0007_remove_pedido_usuario_alter_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='matricula',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
