# Generated by Django 5.2 on 2025-10-05 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelfService', '0008_profile_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='matricula',
            field=models.CharField(default='', max_length=8, unique=True),
            preserve_default=False,
        ),
    ]
